---
title: "Plot/Table"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("~/MRT/sim-omit_mrt.RData")
indep <- omit
load("~/MRT/sim-omit-group.RData")
corgroup <-omit

library(ggplot2)
library(tidyr)
require(data.table)
require(kableExtra)
```


## n = 30 & T =30

```{r echo=FALSE}
indep_3030_wc= subset(indep, n ==30 & tmax == 30 & method == "Weighted and centered")

indep_3030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
corgroup_3030_wc= subset(corgroup, n ==30 & tmax == 30 & method == "Weighted and centered")

corgroup_3030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with pairwise correlation (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
indep_3030_ind= subset(indep, n ==30 & tmax == 30 & method == "GEE independence")

indep_3030_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```




```{r echo=FALSE}
corgroup_3030_ind= subset(corgroup, n ==30 & tmax == 30 & method == "GEE independence")

corgroup_3030_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence with pairwise correlation (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
indep_3030_ar1= subset(indep, n ==30 & tmax == 30 & method == "GEE AR(1)")

indep_3030_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```


```{r echo=FALSE}
corgroup_3030_ar1= subset(corgroup, n ==30 & tmax == 30 & method == "GEE AR(1)")

corgroup_3030_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) with pairwise correlation (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```

## n = 30 & T = 50

```{r echo=FALSE}
indep_3050_wc= subset(indep, n ==30 & tmax == 50 & method == "Weighted and centered")

indep_3050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
corgroup_3050_wc= subset(corgroup, n ==30 & tmax == 50 & method == "Weighted and centered")

corgroup_3050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with pairwise correlation (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
indep_3050_ind= subset(indep, n ==30 & tmax == 50 & method == "GEE independence")

indep_3050_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```




```{r echo=FALSE}
corgroup_3050_ind= subset(corgroup, n ==30 & tmax == 50 & method == "GEE independence")

corgroup_3050_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence with pairwise correlation (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
indep_3050_ar1= subset(indep, n ==30 & tmax == 50 & method == "GEE AR(1)")

indep_3050_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```


```{r echo=FALSE}
corgroup_3050_ar1= subset(corgroup, n ==30 & tmax == 50 & method == "GEE AR(1)")

corgroup_3050_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) with pairwise correlation (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```


## n = 60 & T =30

```{r echo=FALSE}
indep_6030_wc= subset(indep, n ==60 & tmax == 30 & method == "Weighted and centered")

indep_6030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered (n=60, T =30)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
corgroup_6030_wc= subset(corgroup, n ==60 & tmax == 30 & method == "Weighted and centered")

corgroup_6030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group correlation (n=60, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
indep_6030_ind= subset(indep, n ==60 & tmax == 30 & method == "GEE independence")

indep_6030_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence (n=60, T =30)", align = "c") %>%
  kable_styling("striped")
```




```{r echo=FALSE}
corgroup_6030_ind= subset(corgroup, n ==60 & tmax == 30 & method == "GEE independence")

corgroup_6030_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence with group correlation (n=60, T =30)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
indep_6030_ar1= subset(indep, n ==60 & tmax == 30 & method == "GEE AR(1)")

indep_6030_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) (n=60, T =30)", align = "c") %>%
  kable_styling("striped")
```


```{r echo=FALSE}
corgroup_6030_ar1= subset(corgroup, n ==60 & tmax == 30 & method == "GEE AR(1)")

corgroup_6030_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) with group correlation (n=60, T =30)", align = "c") %>%
  kable_styling("striped")
```



## n = 60 & T =50

```{r echo=FALSE}
indep_6050_wc= subset(indep, n ==60 & tmax == 50 & method == "Weighted and centered")

indep_6050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered (n=60, T =50)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
corgroup_6050_wc= subset(corgroup, n ==60 & tmax == 50 & method == "Weighted and centered")

corgroup_6050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group correlation (n=60, T =50)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
indep_6050_ind= subset(indep, n ==60 & tmax == 50 & method == "GEE independence")

indep_6050_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence (n=60, T =50)", align = "c") %>%
  kable_styling("striped")
```




```{r echo=FALSE}
corgroup_6050_ind= subset(corgroup, n ==60 & tmax == 50 & method == "GEE independence")

corgroup_6050_ind[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "	GEE independence with group correlation (n=60, T =50)", align = "c") %>%
  kable_styling("striped")
```

```{r echo=FALSE}
indep_6050_ar1= subset(indep, n ==60 & tmax == 50 & method == "GEE AR(1)")

indep_6050_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) (n=60, T =50)", align = "c") %>%
  kable_styling("striped")
```


```{r echo=FALSE}
corgroup_6050_ar1= subset(corgroup, n ==60 & tmax == 50 & method == "GEE AR(1)")

corgroup_6050_ar1[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "GEE AR(1) with group correlation (n=60, T =50)", align = "c") %>%
  kable_styling("striped")
```

