---
title: "Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
require(data.table)
require(kableExtra)
```


## Tables

### Group settings: 

+ 30 people, 6 groups with 5 people in every group. 

+ 100 people, 4 groups with group sizes 10, 20, 30, and 40.

+ T = 30 & 50


##### 1

+ $\sigma^2 = c(0.1,0.2,0.3,0.4,0.5,0.6)$

+ $\sigma^2 = c(0.5,0.5,0.5,0.5)$

```{r echo=FALSE}
load("~/MRT/all_0.1-0.6-0.5/sim-omit-group.RData")
all <- omit

all_3030_wc= subset(all, n ==30 & tmax == 30 & method == "Weighted and centered")

all_3030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
all_10030_wc= subset(all, n ==100 & tmax == 30 & method == "Weighted and centered")

all_10030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=100, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
all_3050_wc= subset(all, n ==30 & tmax == 50 & method == "Weighted and centered")

all_3050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
all_10050_wc= subset(all, n ==100 & tmax == 50 & method == "Weighted and centered")

all_10050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=100, T =50)", align = "c") %>%
  kable_styling("striped")
```



##### 2

+  $\sigma^2 = c(0.1,0.2,0.3,0.4,0.5,0.6)$

+  $\sigma^2 = c(0.5,0.5,0.5,0.5)$

+ Group errors are changing throughout time, and the correlation matrix has an AR1 structure with $\rho = 0.8$. 


```{r echo=FALSE}
load("~/MRT/changing_0.1-0.6-0.5/sim-omit-group.RData")
change <- omit

change_3030_wc= subset(change, n ==30 & tmax == 30 & method == "Weighted and centered")

change_3030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
change_10030_wc= subset(change, n ==100 & tmax == 30 & method == "Weighted and centered")

change_10030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=100, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
change_3050_wc= subset(change, n ==30 & tmax == 50 & method == "Weighted and centered")

change_3050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
change_10050_wc= subset(change, n ==100 & tmax == 50 & method == "Weighted and centered")

change_10050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=100, T =50)", align = "c") %>%
  kable_styling("striped")
```



##### 3

+  $\sigma^2 = c(0.5,1,1.5,2,2.5,3)$

+  $\sigma^2 = c(2,2,2,2)$

+ Group errors are changing throughout time, and the correlation matrix has an AR1 structure with $\rho = 0.8$. 


```{r echo=FALSE}
load("~/MRT/sim-omit-group.RData")
big <- omit

big_3030_wc= subset(big, n ==30 & tmax == 30 & method == "Weighted and centered")

big_3030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=30, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
big_10030_wc= subset(big, n ==100 & tmax == 30 & method == "Weighted and centered")

big_10030_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=100, T =30)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
big_3050_wc= subset(big, n ==30 & tmax == 50 & method == "Weighted and centered")

big_3050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=30, T =50)", align = "c") %>%
  kable_styling("striped")
```



```{r echo=FALSE}
big_10050_wc= subset(big, n ==100 & tmax == 50 & method == "Weighted and centered")

big_10050_wc[,c("level","truth","est","sec","cpc","rmse")] %>% 
  kable(caption = "Weighted and centered with group structure (n=100, T =50)", align = "c") %>%
  kable_styling("striped")
```






